### ISSUE TITLE
[Feat] 파일 업로드 및 상세정보 입력 기능 구현

### ISSUE THREAD

**Issue by ej070961** [2024-ITM-Capstone-Design/Front#12]
## ✅ Description
- 사용자의 서비스 선택 내용에 따라 조건부로 파일업로드 및 상세정보 입력 기능을 구현
## ✔️ TODO
- [x] 단일이미지만 선택(one): 정보 입력 컴포넌트(제목, 오디오파일, 가사) 구현
- [x] 여러이미지 선택(many): 정보 입력 컴포넌트(제목, 오디오파일), AI 가사 분할 편집 컴포넌트
- [x]  복수선택(both): 정보 입력 컴포넌트(제목, 오디오파일, 가사), AI 가사 분할 편집 컴포넌트
