### ISSUE TITLE
[Feat] 마이페이지 UI 구현 및 API 연결

### ISSUE THREAD

**Issue by ej070961** [2024-ITM-Capstone-Design/Front#31]
## ✅ Description
- 마이페이지 ui 요소를 구현합니다.
## ✔️ TODO

- [x] 사용자 프로필 섹션
- [x] 진행중인 노래 섹션
- [x] 완성된 이미지/비디오 조회 섹션
