### ISSUE TITLE
[Feat] Step5 이미지 생성 결과 조회 UI 구현

### ISSUE THREAD

**Issue by ej070961** [2024-ITM-Capstone-Design/Front#32]
## ✅ Description
- Step5 이미지 생성 결과 조회 페이지 UI를 구현합니다.
## ✔️ TODO

- [x] 이미지 생성결과 조회 페이지 스타일링
- [x] 이미지 개수에 따라 슬라이더 구현
- [x] 타입에 따른 버튼 조건부 렌더링
